### PR TITLE
Add c++ pytorch example

### PR DESCRIPTION
**Pull request by andrewpeterpei**

### CODE REVIEW

**Comment by jeethu** [comment]
Nice PR, @andrewpeterpei ! I've only skimmed it and I've got a few minor comments.

1. It'll be nice to use conan/vcpkg for external deps.
2. Looks like the bulk of the weight in this PR comes from the [csv parsing](https://github.com/vincentlaucsb/csv-parser) code. Perhaps make it a git submodule if using a package manager isn't possible?
3. Instead of hard coding `kRowsPerValidationEra`, can it not be inferred from the tournament data?

**Comment by andrewpeterpei** [comment]
Thanks for taking a look @jeethu!
1. That was an attempt at making the example unopinionated since the C++ ecosystem is unfortunately pretty fragmented. Perhaps we should let people make these (controversial :sweat_smile:) choices for themselves?
2. What's the concern here? LOC? I chose the single header dependency In the same spirit as 1 and for the simplicity, which makes it very easy to later use a package manager of choice.
3. Good point, updated.

**Comment by jeethu** [comment]
>     2. What's the concern here? LOC? I chose the single header dependency In the same spirit as 1 and for the simplicity, which makes it very easy to later use a package manager of choice.

My concern is bloat, which is the antithesis of simplicity. Including a 8.3k line header only library verbatim, to parse a simple csv file and return a vector of Tensors is unconscionable, even in a relatively verbose language like modern C++.

The csv parsing [header](https://github.com/vincentlaucsb/csv-parser) includes a separate [3rd party header only library](https://github.com/mandreyel/mio) to do memory mapped I/O. It’s worth taking a step back and asking: is the added complexity (from a systems perspective, not in terms of LOC) worth it for the simple task of sequentially reading a csv file with a size in the order of a few gigabytes? Perhaps it'd have all been worth the complexity if it was doing everything in a zero-copy fashion, but it isn't. Everything still ends up in the memory. 🙂   

IMHO, It’s quite straightforward to write a simple, no-frills and reasonably performant csv parser which reads a file a line at a time, in less than ~200 lines of C++.

PS: This isn’t about your code, but I ended up grepping through the csv parsing header while writing this. If the reason for its bloat was really performance, I’d have expected a call to the POSIX `madvise()` syscall (and perhaps its Windows equivalent `PrefetchVirtualMemory()`) somewhere. The lack of it makes me wonder if it's a case of complexity for complexity’s sake.

**Comment by kumikoda** [comment]
Thanks for the PR @andrewpeterpei and thanks for the feedback @jeethu 

So I asked @jeethu to help review this code as I am not proficient enough in C++ to give this a good review. At a glance, I like that the example is relatively complete - with a good readme, good comments, formatter configs etc on top of the actual example code itself.
  
I agree with @jeethu that the CSV parsing code seems like a lot but I am also fine with keeping it unopinionated. It seems to me that swapping our the CSV parsing code with a library should be pretty straightforward if someone wanted to do that instead.

My main goal here is to build a good library of example scripts for users from different backgrounds to have something good to reference when getting started. To this end, I think this PR serves the purpose quite well. 

So I am going to merge this PR :) 

Thanks for the contribution @andrewpeterpei !

**Pull request merged**
